Repository rackerlabs/rackspace-how-to, pull requests merged in 2018-02, with the labels that each got.

#2423 BCP-update-permissions-matrix-billing: INFODEV-828
  content/general/detailed-permissions-matrix-for-billing-services.md
Labels: edit: content/SME, edit: style, in progress

#2428 BCP use-pivot-tables-with-your-cloud-billing-invoice
  content/general/use-pivot-tables-with-your-cloud-billing-invoice.md
Labels: ready

#2430 BCP - rackspace-billing-faq
  content/general/rackspace-billing-faq.md
Labels: ready

#2434 BCP - combine-invoices-for-rackspace-managed-and-cloud-accounts
  content/general/combine-invoices-for-rackspace-managed-and-cloud-accounts.md
Labels: ready

#2419 BCP-update-billing-info: INFODEV-824
  content/retired-articles/update-billing-information-for-cloud-hosting.md
Labels: in progress

#2438 BCP-update-faq-role-based-access-control-rbac: INFODEV-909
  content/general/faq-role-based-access-control-rbac.md
Labels: edit: content/SME, edit: style, in progress

#2421 BCP-update-when-billed: INFODEV-826
  content/general/when-am-i-billed-for-my-account.md
Labels: in progress

#2492 Secure private label site
  _assets/img/rackspace-email/secure-existing-webmail-private-label-site/action_secure_sites.png
  _assets/img/rackspace-email/secure-existing-webmail-private-label-site/secure_completed.png
  _assets/img/rackspace-email/secure-existing-webmail-private-label-site/secure_webmail_site.png
  _assets/img/rackspace-email/secure-existing-webmail-private-label-site/site_being_created.png
  _assets/img/rackspace-email/secure-existing-webmail-private-label-site/webmail_sites.png
  content/rackspace-email/secure-existing-webmail-private-label-site.md
Labels: edit: style

#2429 BCP - how-rackspace-bills-for-bandwidth
  content/general/how-rackspace-bills-for-bandwidth.md
Labels: in progress
