Repository rackerlabs/rackspace-how-to, pull requests merged in 2019-11, with the labels that each got.

#3438 Create new article and add new image.
  _assets/img/rackspace-email-archiving/add-and-edit-archive-users/add-edit-user-pic.png
  content/rackspace-email-archiving/early-adopters-add-and-edit-archive-users-in-cloud-office.md
Labels: pending publication

#3462 updates
  content/general/ord1-cr5-cr8-data-center-consolidation-faq.md
Labels: ready to publish - go!

#3433 Add article to troubleshoot error provided-host-name-not-valid
  content/cloud-servers/provided-host-name-not-valid.md
Labels: new
