Repository rackerlabs/rackspace-how-to, pull requests merged in 2020-07, with the labels that each got.

#3814 Create article on checking bandwidth usage
  content/dedicated-hosting/check-bandwidth-usage.md
Labels: new

#3825 Create nova-agent troubleshooting
  content/cloud-servers/troubleshoot-nova-agent-or-rackspace-cloud-server-agent.md
Labels: edit/review: SME/author, new

#3834 retire deprecated article
  content/retired-articles/swift-filesystem-for-hadoop.md
Labels: retired

#3831 Create android-outlook-setup-o365
  content/office-365/set-up-your-office-365-mailbox-in-the-outlook-for-android-mobile-application.md
Labels: new

#3836 Update upgrading-your-exchange-version.md
  content/exchange/upgrading-your-exchange-version.md
Labels: edit/review: SME/author

#3845 Create using-windows-performance-analyzer-to-troubleshoot-performance…
  content/cloud-servers/using-windows-performance-analyzer-to-troubleshoot-performance-issues.md
Labels: new

#3832 Create mac-outlook-setup-o365.md
  content/office-365/set-up-mac-outlook-setup-o365.md
Labels: new

#3839 Create repairing-system-image-with-deployment-image-servicing-and-man…
  content/cloud-servers/repair-a-system-image-with-deployment-image-servicing-and-management-dism.md
Labels: new

#3838 Create installing-iis-on-windows-2012
  content/cloud-servers/install-iis-on-windows-2012.md
Labels: new

#3871 Create installing-lamp-on-debian-10
  content/cloud-servers/install-a-lamp-stack-on-debian-10.md
Labels: edit/review: SME/author, new

#3870 Create installing-lamp-on-ubuntu-1804
  content/cloud-servers/install-a-lamp-stack-on-ubuntu-1804.md
Labels: new

#3852 Create install-nginx-on-ubuntu
  content/cloud-servers/install-nginx-on-ubuntu.md
Labels: new

#3869 Create installing-lamp-on-centos-8
  content/cloud-servers/install-a-lamp-stack-on-centos-8.md
Labels: new

#3872 Create installing-lamp-on-fedora-31
  content/cloud-servers/install-a-lamp-stack-on-fedora-31.md
Labels: new

#3876 Create migrating-between-server-flavors
  content/cloud-servers/migrating-between-server-flavors.md
Labels: new

#3854 Create create-a-reverse-dns-record-in-the-my-rackspace-portal
  content/dedicated-hosting/create-a-reverse-dns-record-in-the-my-rackspace-portal.md
Labels: new

#3867 Create installing-nginx-on-fedora
  content/cloud-servers/install-nginx-on-fedora.md
Labels: new

#3873 Create install-gitlab-on-centos-7
  content/cloud-servers/install-gitlab-on-centos-7.md
Labels: new

#3857 Create install-nextcloud-on-debian-10
  content/cloud-servers/install-nextcloud-on-debian-10.md
Labels: new

#3858 Create install-nextcloud-on-fedora-31
  content/cloud-servers/install-nextcloud-on-fedora-31.md
Labels: new

#3868 Create installing-apache-on-centos-8
  content/cloud-servers/install-apache-on-centos-8.md
Labels: new

#3877 Create install-gitlab-on-debian-10
  content/cloud-servers/install-gitlab-on-debian-10.md
Labels: new

#3853 Create install-nginx-on-windows
  content/cloud-servers/install-nginx-on-windows.md
Labels: new

#3878 Create install-gitlab-on-ubuntu-18-04
  content/cloud-servers/install-gitlab-on-ubuntu-18-04.md
Labels: new

#3882 Create getting-started-with-tasksel-on-debian
  content/cloud-servers/get-started-with-tasksel-on-debian.md
Labels: new

#3881 Create media-server-comparison
  content/cloud-servers/media-server-comparison.md
Labels: new

#3856 Create adding-a-disk-to-a-cluster-shared-volume-on-a-windows-failover…
  content/cloud-servers/add-a-disk-to-a-cluster-shared-volume-on-a-windows-failover-cluster.md
Labels: new

#3859 Create installing-froxlor-on-fedora-31
  content/cloud-servers/installing-froxlor-on-fedora-31.md
Labels: new

#3884 Create getting-started-with-magento-on-debian-10
  content/cloud-servers/get-started-with-magento-on-debian-10.md
Labels: new

#3860 Create froxlor-initial-setup-and-overview
  content/cloud-servers/froxlor-initial-setup-and-overview.md
Labels: new
