Repository rackerlabs/rackspace-how-to, pull requests merged in 2020-05, with the labels that each got.

#3671 Create resetting-cloud-server-network-with-pitchfork
  content/cloud-servers/reset-a-cloud-server-network-with-pitchfork.md
Labels: new

#3677 Create adding-an-ip-to-a-windows-server
  content/cloud-servers/adding-an-ip-to-a-windows-server.md
Labels: new

#3678 Create what-caused-windows-server-shutdown
  content/cloud-servers/troubleshoot-windows-server-shutdowns.md
Labels: new, ready to build

#3679 Create types-of-ssl-certificates
  content/cloud-servers/types-of-ssl-certificates.md
Labels: new, ready to build

#3681 Create windows-low-memory-diagnostics
  content/cloud-servers/windows-low-memory-diagnostics.md
Labels: new

#3682 Create windows-guide-to-resource-monitoring
  content/cloud-servers/guide-to-windows-resource-monitoring.md
Labels: new

#3684 Create checking-linux-configuration-file-for-syntax-errors
  content/cloud-servers/check-linux-configuration-files-for-syntax-errors.md
Labels: new

#3680 Create disabling-a-vhost-in-ubuntu-and-centos-for-apache-and-nginx
  content/cloud-servers/disable-a-vhost-in-the-ubuntu-operating-system-and-centos-for-apache-and-nginx.md
Labels: new

#3690 Create windows-low-disk-diagnostic
  content/cloud-servers/windows-low-disk-diagnostic.md
Labels: new

#3689 Create extend-a-volume-in-windows-server-with-diskpart
  content/cloud-servers/extend-a-volume-in-windows-server-with-diskpart.md
Labels: new

#3693 Create group-policy-fundamentals-in-active-directory
  content/cloud-servers/group-policy-fundamentals-in-active-directory.md
Labels: new

#3695 Create safelist domain o365
  content/office-365/safelist-a-domain-in-exchange-online-m365.md
Labels: edit/review: SME/author, new

#3698 Create disabling-the-admin-user-in-windows
  content/cloud-servers/disable-the-administrator-user-in-windows.md
Labels: new

#3694 Create linux-reboot-commands
  content/cloud-servers/linux-reboot-commands.md
Labels: new

#3700 notify faq
  content/account-management/rackspace-notifications-security-event-faq.md
Labels: edit/review: SME/author, new

#3701 Create ssl-certificate-browser-error
  content/cloud-servers/ssl-certificate-browser-error.md
Labels: new

#3702 Create installing-iis-and-configuring-a-website
  content/cloud-servers/install-iis-and-configure-a-website.md
Labels: new

#3706 Create list-cloud-monitoring-zones-with-pitchfork
  content/cloud-servers/list-cloud-monitoring-zones-with-pitchfork.md
Labels: new

#3713 Create iis-ftp-site-configuration
  content/cloud-servers/permalink: iis-ftp-site-configuration/configure -an-iis-ftp-site.md
Labels: edit/review: SME/author, new

#3715 Create create-sudo-user-in-centos
  content/cloud-servers/create-sudo-user-in-centos.md
Labels: new

#3717 Create installing-php-modules
  content/cloud-servers/installing-php-modules.md
Labels: new

#3721 Add Fortigate article to reset lost admin password
  content/cloud-networks/reset-the-fortigate-vm-administrator-password.md
Labels: new

#3716 Create create-sudo-user-in-ubuntu
  content/cloud-servers/create-a-sudo-user-in-ubuntu.md
Labels: edit: style, new

#3727 Retire Cloud Files Ruby sample article
  content/retired-articles/sample-ruby-application-for-cloud-files.md
Labels: retired

#3722 Create set-or-change-password-in-linux
  content/cloud-servers/set-or-change-a-user-password-in-linux.md
Labels: edit/review: SME/author, new

#3723 Create changing-a-servers-hostname-in-ubuntu
  content/cloud-servers/change-a-server-hostname-in-the-ubuntu-operating-system.md
Labels: edit/review: SME/author, new

#3724 Create enable-ssh-remote-root-login-ubuntu-and-centos
  content/cloud-servers/enable-ssh-remote-root-login-on-centos-and-the-ubuntu-operating-system.md
Labels: edit/review: SME/author, new

#3725 Create base-service-commands-in-Centos-7
  content/cloud-servers/base-service-commands-in-Centos-7.md
Labels: edit/review: SME/author, new
