Repository rackerlabs/rackspace-how-to, pull requests merged in 2020-06, with the labels that each got.

#3735 Create dns-basics
  content/general/dns-basics.md
Labels: new, ready to publish - go!

#3737 Create create-user-and-grant-permissions-in-mysql
  content/cloud-servers/create-a-new-user-and-grant-permissions-in-mysql.md
Labels: new

#3739 Create deleting-downloaded-windows-updates
  content/cloud-servers/delete-downloaded-windows-updates.md
Labels: edit/review: SME/author, new

#3741 Create basic-ufw-firewall-management
  content/cloud-servers/basic-ufw-firewall-management.md
Labels: new

#3742 Create basic-iptables-firewall-management
  basic-iptables-firewall-management.md
Labels: new

#3760 Create managing-linux-user-groups
  content/cloud-servers/manage-linux-user-groups.md
Labels: new, ready to publish - go!

#3761 Create checking-network-connectivity-on-a-server
  content/cloud-servers/check-network-connectivity-on-a-linux-server.md
Labels: new, ready to publish - go!

#3773 Create copy-and-paste-to-remote-desktop-troubleshooting
  content/cloud-servers/troubleshoot-copy-and-paste-errors-with-remote-desktop.md
Labels: new, ready to publish - go!

#3743 Create basic-firewalld-firewall-management
  content/cloud-servers/basic-firewalld-firewall-management.md
Labels: new

#3753 Create managing-virtual-machines
  content/dedicated-hosting/managing-virtual-machines.md
Labels: new

#3770 Create managing-packages-in-rhel-based-distributions
  content/cloud-servers/manage-packages-in-rhel-based-distributions.md
Labels: new, ready to publish - go!

#3774 Create app-pool-troubleshooting-basics
  content/cloud-servers/basic-application-pool-troubleshooting.md
Labels: new

#3775 Create troubleshooting-remote-desktop-services
  content/cloud-servers/troubleshoot-remote-dekstop-services.md
Labels: new

#3776 Create windows-local-group-policy
  content/cloud-servers/windows-local-group-policy.md
Labels: new

#3777 Create viewing-firewall-version-in-the-rackspace-portal
  content/dedicated-hosting/view-the-firewall-version-in-the-rackspace-portal.md
Labels: new

#3778 Create active-directory-creating-managing-and-deleting-users-and-groups
  content/cloud-servers/create-manage-and-delete-users-and-groups-in-active-directory.md
Labels: new

#3769 Create viewing-system-users-in-linux
  content/cloud-servers/viewing-system-users-in-linux.md
Labels: new

#3779 Create configuring-internet-connection-firewall-for-iis
  content/cloud-servers/configue-an-internet-connection-firewall-for-iis.md
Labels: new, ready to publish - go!

#3780 Create modify-group-in-active-directory-group-policy-manager
  content/cloud-servers/modify-the-password-policy-in-the-active-directory-group-policy-manager.md
Labels: new, ready to publish - go!

#3785 Editorial changes
  content/cloud-servers/check-network-connectivity-on-a-linux-server.md
Labels: ready to publish - go!

#3786 Editorial changes
  content/cloud-servers/troubleshoot-copy-and-paste-errors-with-remote-desktop.md
Labels: ready to publish - go!

#3787 Editorial changes
  content/cloud-servers/manage-linux-user-groups.md
Labels: ready to publish - go!

#3788 Editorial changes
  content/cloud-servers/basic-application-pool-troubleshooting.md
Labels: ready to publish - go!

#3789 Editorial changes
  content/cloud-servers/troubleshoot-remote-dekstop-services.md
Labels: ready to publish - go!

#3790 Editorial changes
  content/cloud-servers/windows-local-group-policy.md
Labels: ready to publish - go!

#3792 Editorial changes
  content/dedicated-hosting/view-the-firewall-version-in-the-rackspace-customer-portal.md
Labels: ready to publish - go!

#3793 Editorial changes
  content/cloud-servers/create-manage-and-delete-users-and-groups-in-active-directory.md
Labels: ready to publish - go!

#3781 add new cloudflare product content
  _assets/img/rms-cloudflare/how-cloudflare-works/cloudflare-diagram.png
  _assets/img/rms-cloudflare/understanding-bot-management/good-bad-bots.png
  content/index.md
  content/rms-cloudflare/all.md
  content/rms-cloudflare/cloudflare-faq.md
  content/rms-cloudflare/how-cloudflare-works.md
  content/rms-cloudflare/index.md
  content/rms-cloudflare/supported-features.md
  content/rms-cloudflare/understanding-bot-management.md
Labels: new

#3783 Create checking-port-use-in-linux
  content/cloud-servers/checking-port-use-in-linux.md
Labels: new

#3794 Create creating-apache-redirects
  content/cloud-servers/creating-apache-redirects.md
Labels: new

#3796 Create windows-event-viewer
  content/cloud-servers/windows-event-viewer-overview.md
Labels: new

#3797 Create truncating-and-shrinking-log-files-in-sql-server
  content/cloud-servers/truncate-and-shrink-log-files-in-sql-server.md
Labels: new

#3791 Create using-event-viewer-to-troubleshoot-system-freezing
  content/cloud-servers/use-event-viewer-to-troubleshoot-system-freezing.md
Labels: new

#3800 Create block-an-ip-address-on-a-Linux-server
  content/cloud-servers/block-an-ip-address-on-a-Linux-server.md
Labels: new

#3801 Create block-an-ip-address-on-windows-server
  content/cloud-servers/block-an-ip-address-on-a-windows-server.md
Labels: edit/review: SME/author, new

#3798 Create copy-files-with-scp-and-rsync/
  content/cloud-servers/copy-files-with-scp-and-rsync.md
Labels: edit/review: SME/author, new

#3806 Create working-with-zip-files-in-Linux
  content/cloud-servers/work-with-zip-files-in-linux.md
Labels: new, ready to publish - go!

#3807 Create hostname-change-on-centos-6
  content/cloud-servers/change-the-hostname-change-on-centos-6-servers.md
Labels: new, ready to publish - go!

#3808 Create windows-bug-check-analysis
  content/cloud-servers/windows-bug-check-analysis.md
Labels: new

#3809 Create change-ssh-port-in-centos-rhel
  content/cloud-servers/change-the-ssh-port-in-centos-and-redhat.md
Labels: new

#3810 Create change-ssh-port-in-ubuntu
  content/cloud-servers/change-the-ssh-port-in-the-linux-ubuntu-operating-system.md
Labels: new

#3811 Create article on how to reset a VPN user password
  content/dedicated-hosting/reset-your-cisco-asa-vpn-user-password-by-using-the-rackspace-portal.md
Labels: new

#3813 Create troubleshooting-iis-high-resource-usage
  content/cloud-servers/troubleshoot-iis-high-resource-usage.md
Labels: new

#3815 Create add-an-additional-rdp-license-to-windows-server-2012r2
  content/cloud-servers/add-an-additional-rdp-license-to-windows-server-2012-r2.md
Labels: new

#3816 Create install-nginx-on-centos-6
  content/cloud-servers/install-nginx-on-centos-6.md
Labels: edit/review: SME/author, new

#3817 Create rds-client-disconnected-codes-and-reasons
  content/cloud-servers/rds-client-disconnected-codes-and-reasons.md
Labels: new
